baseURL = 'https://yeer39905-oss.github.io/blog/'

languageCode = 'zh-cn'

title = "Cinthia's blogs"

theme = "PaperMod"

[params]
  author = "Cinthia"
  description = "记录计算机学习过程"

  defaultTheme = "auto"

  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

 [params.profileMode]
  enabled = true
  title = "Cinthia"
  subtitle = "Information Security Student | AI | Algorithms"
  imageUrl = "/blog/avatar.jpg"
  imageTitle = "avatar"